panda_gripper:
  type: position_controllers/GripperActionController
  joint: panda_finger_joint1
  action_monitor_rate: 20
  goal_tolerance: 0.001
  max_effort: 100
  stall_velocity_threshold: 0.001
stall_timeout: 0.5
